name: bank-auc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - lightgbm
  - xgboost
  - catboost
  - matplotlib
  - seaborn
  - jupyterlab
  - pip
  - pip:
      - pre-commit
      - ruff
      - black
      - isort
      - nbstripout
      - kmodes
      - gower
