name: bank-auc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - numpy=1.26.4
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - lightgbm=4.6.0
  - xgboost=3.0.3
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - ipykernel
  - jupyterlab=4.3.*
  - jupyterlab-lsp=5.1.*
  - python-lsp-server=1.12.*
  - imbalanced-learn=0.13.0
  - numba
  - scipy=1.13.1
  - statsmodels
  - yaml
  - ruamel.yaml
  - black
  - isort
  - ruff
  - nbstripout
  - pre-commit
  - pandas-stubs=2.2.3.250308
  - pyarrow
  - pip:
      - catboost==1.2.8
      - shap==0.48.0
      - kmodes==0.12.2
      - gower==0.1.2
      - jupyterlab-code-formatter==3.0.2
      - pyright==1.1.394
      - python-dotenv==1.1.1
